
package com.example.wsdltopojo.ack;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceSoap {


    /**
     * 
     * @param memberCode
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CheckConnection", action = "http://tempuri.org/CheckConnection")
    @WebResult(name = "CheckConnectionResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckConnection", targetNamespace = "http://tempuri.org/", className = "com.example.wsdltopojo.ack.CheckConnection")
    @ResponseWrapper(localName = "CheckConnectionResponse", targetNamespace = "http://tempuri.org/", className = "com.example.wsdltopojo.ack.CheckConnectionResponse")
    public int checkConnection(
        @WebParam(name = "memberCode", targetNamespace = "http://tempuri.org/")
        String memberCode);

    /**
     * 
     * @param getFileResponse
     * @param memberCode
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ReceiveAck", action = "http://tempuri.org/ReceiveAck")
    @WebResult(name = "ReceiveAckResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceiveAck", targetNamespace = "http://tempuri.org/", className = "com.example.wsdltopojo.ack.ReceiveAck")
    @ResponseWrapper(localName = "ReceiveAckResponse", targetNamespace = "http://tempuri.org/", className = "com.example.wsdltopojo.ack.ReceiveAckResponse")
    public int receiveAck(
        @WebParam(name = "memberCode", targetNamespace = "http://tempuri.org/")
        String memberCode,
        @WebParam(name = "getFileResponse", targetNamespace = "http://tempuri.org/Services.asmx/getResponseFile")
        CFileContent getFileResponse);

}
